[info]
version = "3.0" # --REQUIRED--
# Description : Plugin mod-version
# Format      : <int>[.<int>], where first <int> is MAJOR version and second <int> is MINOR
# Note        : If MINOR is omitted, bulb will default to MAJOR.0

type    = "plugin"
# Description : Type of the plugin
# Format      : One of the following: "plugin", "syntax"
